// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUT0u7Sb_fWUo4uf-mjkyIpLkxBSig5r4',
    appId: '1:294988032102:web:5bccea00b467ad11e225a7',
    messagingSenderId: '294988032102',
    projectId: 'lineage-5b6e3',
    authDomain: 'lineage-5b6e3.firebaseapp.com',
    storageBucket: 'lineage-5b6e3.firebasestorage.app',
    measurementId: 'G-DZ2WG0RJXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqHmCzMXTI4DGNSNvsdm5DEELxK91FAE4',
    appId: '1:294988032102:android:940c20ea4c1c83e2e225a7',
    messagingSenderId: '294988032102',
    projectId: 'lineage-5b6e3',
    storageBucket: 'lineage-5b6e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFGukuVNSVUVljYZs22o1YUIqtw3RcWaM',
    appId: '1:294988032102:ios:1a5efefc62cd65cfe225a7',
    messagingSenderId: '294988032102',
    projectId: 'lineage-5b6e3',
    storageBucket: 'lineage-5b6e3.firebasestorage.app',
    iosBundleId: 'com.ahjkuio.lineageFamilyApp',
  );

}